// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MealMind",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "MealMind",
            targets: ["AppModule"],
            bundleIdentifier: "com.arelekar.MealMind",
            teamIdentifier: "8WFJ8QVLC7",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: "public.app-category.food-and-drink",
            additionalInfoPlistContentFilePath: "Info.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources"),
                .copy("IngredientCategoryClassifier.mlmodelc")
            ],
            swiftSettings: [
                .define("SWIFT_PACKAGE")
            ]
        )
    ],
    swiftLanguageVersions: [.v5]
)